server:
  port: 7200
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306/eStore_dev?allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
# noinspection undefined

image-path-user: "dev/images/user/"
# noinspection undefined
image-path-category: "dev/images/category/"
# noinspection undefined
image-path-product: "dev/images/product/"
